### ISSUE TITLE
Proposal feedback / tips

### ISSUE THREAD

**Issue by donbowen** [JerseyK/Final-Project_Sunset#2]
I come late but bearing gifts. The thing I thought I was going to ask you to do, we will skip. I can elaborate in person. Your data discussion is in parts now moot because you will start with a (dirty) dataset already assembled. The proposal needs to change. The key to your project remains execution on the dashboard, but you'll need to convince me you cleaned this data well. 

Gift 1: [This attached data-cust_supply_2019_2022.zip](https://github.com/JerseyK/Final-Project_Sunset/files/11264396/cust_supply_2019_2022.zip)
- "Compustat Customer Supplier" data. Sometime aka the "Segments" data. 
- This is the Major Customers firms report in 10-Ks, where the customer accounts for more than 5% (10%?) of firm sales. 
- This is the raw data. I have not filtered or cleaned it. You'll need to read about it and clean it. 
- These variables describe the firm a row of data: srcdate	conm	tic	cusip	cik	sic gvkey 
- These variables describe the customer of the firm and say something about the relationship type: cid	cnms	ctype	gareac	gareat	salecs	sid	stype
   - You want to filter to `ctype == COMPANY`
   - Many rows with company say "CNMS" (customer name) is Not Reported. 

Gift 2: Filter this dataset using cik to the S&P500 firms. Then output a csv of the gvkeys of the firms. (Should be ~500 rows.) Send to me along with a request about which variables you want. I'll send back accounting data on these firms for 2018-2022.

**Comment by donbowen** [comment]
@kag223 @Qiyu6769 @JerseyK

**Comment by JerseyK** [comment]
@donbowen Thank you for the gifts!!

Based on your feedback we modified our [proposal.md](https://github.com/JerseyK/Final-Project_Sunset/blob/dd7bb7c21d9b1d5af0a9735f73761de03c4073c1/proposal/proposal.md) to align with the provided dataset.

Our changes:
- We deleted any mentioning of scraping data
- We included new steps involving filtering and cleaning the provided dataset(s)
- We modified the usage of 10Ks (looking at them to verify data rather than scraping data from them)

\- Sunset

**Comment by JerseyK** [comment]
@donbowen 

After cleaning the dataset you provided and filtering using cik with the SP500 data we only ended up with about 150 unique company (sellers) Gvkeys. We then further looked at the data and realized that some companies, such as AAPL did not report to any specific companies, but rather reported selling to other countries and other markets instead.

Therefore we just decided against filtering just companies because it would provide a more holistic view of the seller company's finance. This also yielded about 350 unique company (sellers) Gvkeys. We have made this decision after submitting the proposal update.

[Here is the CSV with the ~350 gvkeys.](https://github.com/JerseyK/Final-Project_Sunset/blob/12916454d2c7f8b98e3d6d7a5d5e49abbff46423/inputs/listkeys.csv)

Variables we would like for accounting data:
- Net income
- Cost of goods sold
- Sales 
- Gross profit
- Earnings per share
- Inventory


Thank you so much!
\- Sunset

**Comment by donbowen** [comment]
Please find the name of the corresponding variables

The documentation is here:
https://sites.bu.edu/qm222projectcourse/files/2014/08/compustat_users_guide-2003.pdf

Other documentation on the web might help you figure out the varnames
(below)

For example, I use these as a "standard" set of controls:


*======================================================================
*   DEFINE OTHER VARIABLES
*======================================================================

g td = (dlc+dltt)

g td_a = td/at

g short_debt = dlc/td // % 1 yr debt
g long_debt_dum = (dltt > 0) if dltt != . // any long term debt?

g me = csho*prcc_f

g td_mv = td/(td+me)

g dltt_a   = dltt / at

g l_a = log(at)

g l_sale = log(sale)

g prof_a = oibdp/at // aka ROA

*g prof_dum = (prof_a > 0) if prof_a != .

g mb = (at - ceq + (csho*prcc_f))/at

g ppe_a = ppent/at // aka tangibility

g cash_a = che/at

g xrd_a = xrd / at
replace xrd_a = 0 if xrd_a == .

g capx_a = capx/at

g div_d = .
replace div_d = 0 if dv == 0
replace div_d = 1 if dv >0
replace div_d = . if dv == .

g dv_a = dv/at

g invopps_FG09 = (prcc_f * cshpri + pstkl + dltt + dlc - txditc) / at

bysort gvkey (fyear): g sales_g = (sale/sale[_n-1])-1 if fyear ==
fyear[_n-1] + 1

*bysort gvkey (fyear): g emp_g = (emp/emp[_n-1])-1 if fyear == fyear[_n-1]
+ 1

g temp = fyear if prcc_f != .
bysort gvkey (fyear): egen first_fyear_with_price = min(temp)
count if first_fyear_with_price > fyear & first_fyear_with_price != .
g age = fyear - first_fyear_with_price
replace age = . if age < 0
drop temp  first_fyear_with_price

g atr = txt / (txt + ib)
replace atr = 0 if txt < 0
replace atr = 1 if txt > ib
replace atr = . if txt == . | ib == .

egen temp = rowtotal(ib dp txt xint), missing
g smalltaxlosscarry   = (tlcf > 0) & (tlcf < ib + dp + txt + xint) if tlcf
!= . & temp != .
g largetaxlosscarry = (tlcf > 0) & (tlcf > ib + dp + txt + xint) if tlcf !=
. & temp != .
// blank if tlcf blank OR if all of (ib dp txt xint) blank

g l_emp = log(1+emp)
g l_ppent = log(1+ppent)
g l_laborratio = log(ppent/emp)


The variable names I have are here:


Contains data from ccm.dta
 Observations:        26,905
    Variables:           950                  26 Apr 2023 11:56
--------------------------------------------------------------------------------------------------------
Variable      Storage   Display    Value
    name         type    format    label      Variable label
--------------------------------------------------------------------------------------------------------
lpermno         double  %10.0g
lpermco         double  %10.0g
gvkey           str6    %9s
datadate        double  %td
fyear           double  %10.0g
indfmt          str4    %9s
consol          str1    %9s
popsrc          str1    %9s
datafmt         str3    %9s
tic             str6    %9s
cusip           str9    %9s
conm            str29   %29s
acctchg         str8    %9s
acctstd         str2    %9s
acqmeth         str2    %9s
adrr            double  %10.0g
ajex            double  %10.0g
ajp             double  %10.0g
bspr            str2    %9s
compst          str2    %9s
curcd           str3    %9s
curncd          str3    %9s
currtr          double  %10.0g
curuscn         double  %10.0g
final           str1    %9s
fyr             double  %10.0g
ismod           double  %10.0g
ltcm            str1    %9s
ogm             str1    %9s
pddur           double  %10.0g
scf             double  %10.0g
src             double  %10.0g
stalt           str2    %9s
udpl            str2    %9s
upd             double  %10.0g
apdedate        double  %td
fdate           double  %td
pdate           double  %td
acchg           double  %10.0g
acco            double  %10.0g
accrt           double  %10.0g
acdo            double  %10.0g
aco             double  %10.0g
acodo           double  %10.0g
acominc         double  %10.0g
acox            double  %10.0g
acoxar          double  %10.0g
acqao           double  %10.0g
acqcshi         double  %10.0g
acqgdwl         double  %10.0g
acqic           double  %10.0g
acqintan        double  %10.0g
acqinvt         double  %10.0g
acqlntal        double  %10.0g
acqniintc       double  %10.0g
acqppe          double  %10.0g
acqsc           double  %10.0g
act             double  %10.0g
adpac           double  %10.0g
aedi            double  %10.0g
afudcc          double  %10.0g
afudci          double  %10.0g
aldo            double  %10.0g
am              double  %10.0g
amc             double  %10.0g
amdc            double  %10.0g
amgw            double  %10.0g
ano             double  %10.0g
ao              double  %10.0g
aocidergl       double  %10.0g
aociother       double  %10.0g
aocipen         double  %10.0g
aocisecgl       double  %10.0g
aodo            double  %10.0g
aol2            double  %10.0g
aoloch          double  %10.0g
aox             double  %10.0g
ap              double  %10.0g
apalch          double  %10.0g
apb             double  %10.0g
apc             double  %10.0g
apofs           double  %10.0g
aqa             double  %10.0g
aqc             double  %10.0g
aqd             double  %10.0g
aqeps           double  %10.0g
aqi             double  %10.0g
aqp             double  %10.0g
aqpl1           double  %10.0g
aqs             double  %10.0g
arb             double  %10.0g
arc             double  %10.0g
arce            double  %10.0g
arced           double  %10.0g
arceeps         double  %10.0g
artfs           double  %10.0g
at              double  %10.0g
aul3            double  %10.0g
autxr           double  %10.0g
balr            double  %10.0g
banlr           double  %10.0g
bast            double  %10.0g
bastr           double  %10.0g
batr            double  %10.0g
bcef            double  %10.0g
bclr            double  %10.0g
bcltbl          double  %10.0g
bcnlr           double  %10.0g
bcrbl           double  %10.0g
bct             double  %10.0g
bctbl           double  %10.0g
bctr            double  %10.0g
billexce        double  %10.0g
bkvlps          double  %10.0g
bltbl           double  %10.0g
ca              double  %10.0g
capr1           double  %10.0g
capr2           double  %10.0g
capr3           double  %10.0g
caps            double  %10.0g
capsft          double  %10.0g
capx            double  %10.0g
capxv           double  %10.0g
cb              double  %10.0g
cbi             double  %10.0g
cdpac           double  %10.0g
cdvc            double  %10.0g
ceiexbill       double  %10.0g
ceq             double  %10.0g
ceql            double  %10.0g
ceqt            double  %10.0g
cfbd            double  %10.0g
cfere           double  %10.0g
cfo             double  %10.0g
cfpdo           double  %10.0g
cga             double  %10.0g
cgri            double  %10.0g
cgti            double  %10.0g
cgui            double  %10.0g
ch              double  %10.0g
che             double  %10.0g
chech           double  %10.0g
chs             double  %10.0g
ci              double  %10.0g
cibegni         double  %10.0g
cicurr          double  %10.0g
cidergl         double  %10.0g
cimii           double  %10.0g
ciother         double  %10.0g
cipen           double  %10.0g
cisecgl         double  %10.0g
citotal         double  %10.0g
cld2            double  %10.0g
cld3            double  %10.0g
cld4            double  %10.0g
cld5            double  %10.0g
clfc            double  %10.0g
clfx            double  %10.0g
clg             double  %10.0g
clis            double  %10.0g
cll             double  %10.0g
cllc            double  %10.0g
clo             double  %10.0g
clrll           double  %10.0g
clt             double  %10.0g
cmp             double  %10.0g
cnltbl          double  %10.0g
cogs            double  %10.0g
cpcbl           double  %10.0g
cpdoi           double  %10.0g
cpnli           double  %10.0g
cppbl           double  %10.0g
cprei           double  %10.0g
crv             double  %10.0g
crvnli          double  %10.0g
cshfd           double  %10.0g
cshi            double  %10.0g
csho            double  %10.0g
cshpri          double  %10.0g
cshr            double  %10.0g
cshrc           double  %10.0g
cshrp           double  %10.0g
cshrso          double  %10.0g
cshrt           double  %10.0g
cshrw           double  %10.0g
cstk            double  %10.0g
cstkcv          double  %10.0g
cstke           double  %10.0g
dbi             double  %10.0g
dc              double  %10.0g
dclo            double  %10.0g
dcom            double  %10.0g
dcpstk          double  %10.0g
dcs             double  %10.0g
dcvsr           double  %10.0g
dcvsub          double  %10.0g
dcvt            double  %10.0g
dd              double  %10.0g
dd1             double  %10.0g
dd2             double  %10.0g
dd3             double  %10.0g
dd4             double  %10.0g
dd5             double  %10.0g
depc            double  %10.0g
derac           double  %10.0g
deralt          double  %10.0g
derhedgl        double  %10.0g
derlc           double  %10.0g
derllt          double  %10.0g
dfpac           double  %10.0g
dfs             double  %10.0g
dfxa            double  %10.0g
diladj          double  %10.0g
dilavx          double  %10.0g
dlc             double  %10.0g
dlcch           double  %10.0g
dltis           double  %10.0g
dlto            double  %10.0g
dltp            double  %10.0g
dltr            double  %10.0g
dltsub          double  %10.0g
dltt            double  %10.0g
dm              double  %10.0g
dn              double  %10.0g
do              double  %10.0g
donr            double  %10.0g
dp              double  %10.0g
dpacb           double  %10.0g
dpacc           double  %10.0g
dpacli          double  %10.0g
dpacls          double  %10.0g
dpacme          double  %10.0g
dpacnr          double  %10.0g
dpaco           double  %10.0g
dpacre          double  %10.0g
dpact           double  %10.0g
dpc             double  %10.0g
dpdc            double  %10.0g
dpltb           double  %10.0g
dpret           double  %10.0g
dpsc            double  %10.0g
dpstb           double  %10.0g
dptb            double  %10.0g
dptc            double  %10.0g
dptic           double  %10.0g
dpvieb          double  %10.0g
dpvio           double  %10.0g
dpvir           double  %10.0g
drc             double  %10.0g
drci            double  %10.0g
drlt            double  %10.0g
ds              double  %10.0g
dt              double  %10.0g
dtea            double  %10.0g
dted            double  %10.0g
dteeps          double  %10.0g
dtep            double  %10.0g
dudd            double  %10.0g
dv              double  %10.0g
dvc             double  %10.0g
dvdnp           double  %10.0g
dvintf          double  %10.0g
dvp             double  %10.0g
dvpa            double  %10.0g
dvpd            double  %10.0g
dvpdp           double  %10.0g
dvpibb          double  %10.0g
dvrpiv          double  %10.0g
dvrre           double  %10.0g
dvsco           double  %10.0g
dvt             double  %10.0g
dxd2            double  %10.0g
dxd3            double  %10.0g
dxd4            double  %10.0g
dxd5            double  %10.0g
ea              double  %10.0g
ebit            double  %10.0g
ebitda          double  %10.0g
eiea            double  %10.0g
emol            double  %10.0g
emp             double  %10.0g
epsfi           double  %10.0g
epsfx           double  %10.0g
epspi           double  %10.0g
epspx           double  %10.0g
esopct          double  %10.0g
esopdlt         double  %10.0g
esopnr          double  %10.0g
esopr           double  %10.0g
esopt           double  %10.0g
esub            double  %10.0g
esubc           double  %10.0g
excadj          double  %10.0g
exre            double  %10.0g
fatb            double  %10.0g
fatc            double  %10.0g
fatd            double  %10.0g
fate            double  %10.0g
fatl            double  %10.0g
fatn            double  %10.0g
fato            double  %10.0g
fatp            double  %10.0g
fca             double  %10.0g
fdfr            double  %10.0g
fea             double  %10.0g
fel             double  %10.0g
ffo             double  %10.0g
ffs             double  %10.0g
fiao            double  %10.0g
finaco          double  %10.0g
finao           double  %10.0g
fincf           double  %10.0g
finch           double  %10.0g
findlc          double  %10.0g
findlt          double  %10.0g
finivst         double  %10.0g
finlco          double  %10.0g
finlto          double  %10.0g
finnp           double  %10.0g
finrecc         double  %10.0g
finreclt        double  %10.0g
finrev          double  %10.0g
finxint         double  %10.0g
finxopr         double  %10.0g
fopo            double  %10.0g
fopox           double  %10.0g
fopt            double  %10.0g
fsrco           double  %10.0g
fsrct           double  %10.0g
fuseo           double  %10.0g
fuset           double  %10.0g
gbbl            double  %10.0g
gdwl            double  %10.0g
gdwlam          double  %10.0g
gdwlia          double  %10.0g
gdwlid          double  %10.0g
gdwlieps        double  %10.0g
gdwlip          double  %10.0g
geqrv           double  %10.0g
gla             double  %10.0g
glcea           double  %10.0g
glced           double  %10.0g
glceeps         double  %10.0g
glcep           double  %10.0g
gld             double  %10.0g
gleps           double  %10.0g
gliv            double  %10.0g
glp             double  %10.0g
govgr           double  %10.0g
govtown         double  %10.0g
gp              double  %10.0g
gphbl           double  %10.0g
gplbl           double  %10.0g
gpobl           double  %10.0g
gprbl           double  %10.0g
gptbl           double  %10.0g
gwo             double  %10.0g
hedgegl         double  %10.0g
iaeq            double  %10.0g
iaeqci          double  %10.0g
iaeqmi          double  %10.0g
iafici          double  %10.0g
iafxi           double  %10.0g
iafxmi          double  %10.0g
iali            double  %10.0g
ialoi           double  %10.0g
ialti           double  %10.0g
iamli           double  %10.0g
iaoi            double  %10.0g
iapli           double  %10.0g
iarei           double  %10.0g
iasci           double  %10.0g
iasmi           double  %10.0g
iassi           double  %10.0g
iasti           double  %10.0g
iatci           double  %10.0g
iati            double  %10.0g
iatmi           double  %10.0g
iaui            double  %10.0g
ib              double  %10.0g
ibadj           double  %10.0g
ibbl            double  %10.0g
ibc             double  %10.0g
ibcom           double  %10.0g
ibki            double  %10.0g
ibmii           double  %10.0g
icapt           double  %10.0g
idiis           double  %10.0g
idilb           double  %10.0g
idilc           double  %10.0g
idis            double  %10.0g
idist           double  %10.0g
idit            double  %10.0g
idits           double  %10.0g
iire            double  %10.0g
initb           double  %10.0g
intan           double  %10.0g
intano          double  %10.0g
intc            double  %10.0g
intpn           double  %10.0g
invch           double  %10.0g
invfg           double  %10.0g
invo            double  %10.0g
invofs          double  %10.0g
invreh          double  %10.0g
invrei          double  %10.0g
invres          double  %10.0g
invrm           double  %10.0g
invt            double  %10.0g
invwip          double  %10.0g
iobd            double  %10.0g
ioi             double  %10.0g
iore            double  %10.0g
ip              double  %10.0g
ipabl           double  %10.0g
ipc             double  %10.0g
iphbl           double  %10.0g
iplbl           double  %10.0g
ipobl           double  %10.0g
iptbl           double  %10.0g
ipti            double  %10.0g
ipv             double  %10.0g
irei            double  %10.0g
irent           double  %10.0g
irii            double  %10.0g
irli            double  %10.0g
irnli           double  %10.0g
irsi            double  %10.0g
iseq            double  %10.0g
iseqc           double  %10.0g
iseqm           double  %10.0g
isfi            double  %10.0g
isfxc           double  %10.0g
isfxm           double  %10.0g
isgr            double  %10.0g
isgt            double  %10.0g
isgu            double  %10.0g
islg            double  %10.0g
islgc           double  %10.0g
islgm           double  %10.0g
islt            double  %10.0g
isng            double  %10.0g
isngc           double  %10.0g
isngm           double  %10.0g
isotc           double  %10.0g
isoth           double  %10.0g
isotm           double  %10.0g
issc            double  %10.0g
issm            double  %10.0g
issu            double  %10.0g
ist             double  %10.0g
istc            double  %10.0g
istm            double  %10.0g
isut            double  %10.0g
itcb            double  %10.0g
itcc            double  %10.0g
itci            double  %10.0g
ivaco           double  %10.0g
ivaeq           double  %10.0g
ivao            double  %10.0g
ivch            double  %10.0g
ivgod           double  %10.0g
ivi             double  %10.0g
ivncf           double  %10.0g
ivpt            double  %10.0g
ivst            double  %10.0g
ivstch          double  %10.0g
lcabg           double  %10.0g
lcacl           double  %10.0g
lcacr           double  %10.0g
lcag            double  %10.0g
lcal            double  %10.0g
lcalt           double  %10.0g
lcam            double  %10.0g
lcao            double  %10.0g
lcast           double  %10.0g
lcat            double  %10.0g
lco             double  %10.0g
lcox            double  %10.0g
lcoxar          double  %10.0g
lcoxdr          double  %10.0g
lct             double  %10.0g
lcuacu          double  %10.0g
li              double  %10.0g
lif             double  %10.0g
lifr            double  %10.0g
lifrp           double  %10.0g
lloml           double  %10.0g
lloo            double  %10.0g
llot            double  %10.0g
llrci           double  %10.0g
llrcr           double  %10.0g
llwoci          double  %10.0g
llwocr          double  %10.0g
lno             double  %10.0g
lo              double  %10.0g
lol2            double  %10.0g
loxdr           double  %10.0g
lqpl1           double  %10.0g
lrv             double  %10.0g
ls              double  %10.0g
lse             double  %10.0g
lst             double  %10.0g
lt              double  %10.0g
lul3            double  %10.0g
mib             double  %10.0g
mibn            double  %10.0g
mibt            double  %10.0g
mii             double  %10.0g
mrc1            double  %10.0g
mrc2            double  %10.0g
mrc3            double  %10.0g
mrc4            double  %10.0g
mrc5            double  %10.0g
mrct            double  %10.0g
mrcta           double  %10.0g
msa             double  %10.0g
msvrv           double  %10.0g
mtl             double  %10.0g
nat             double  %10.0g
nco             double  %10.0g
nfsr            double  %10.0g
ni              double  %10.0g
niadj           double  %10.0g
nieci           double  %10.0g
niint           double  %10.0g
niintpfc        double  %10.0g
niintpfp        double  %10.0g
niit            double  %10.0g
nim             double  %10.0g
nio             double  %10.0g
nipfc           double  %10.0g
nipfp           double  %10.0g
nit             double  %10.0g
nits            double  %10.0g
nopi            double  %10.0g
nopio           double  %10.0g
np              double  %10.0g
npanl           double  %10.0g
npaore          double  %10.0g
nparl           double  %10.0g
npat            double  %10.0g
nrtxt           double  %10.0g
nrtxtd          double  %10.0g
nrtxteps        double  %10.0g
oancf           double  %10.0g
ob              double  %10.0g
oiadp           double  %10.0g
oibdp           double  %10.0g
opeps           double  %10.0g
opili           double  %10.0g
opincar         double  %10.0g
opini           double  %10.0g
opioi           double  %10.0g
opiri           double  %10.0g
opiti           double  %10.0g
oprepsx         double  %10.0g
optca           double  %10.0g
optdr           double  %10.0g
optex           double  %10.0g
optexd          double  %10.0g
optfvgr         double  %10.0g
optgr           double  %10.0g
optlife         double  %10.0g
optosby         double  %10.0g
optosey         double  %10.0g
optprcby        double  %10.0g
optprcca        double  %10.0g
optprcex        double  %10.0g
optprcey        double  %10.0g
optprcgr        double  %10.0g
optprcwa        double  %10.0g
optrfr          double  %10.0g
optvol          double  %10.0g
palr            double  %10.0g
panlr           double  %10.0g
patr            double  %10.0g
pcl             double  %10.0g
pclr            double  %10.0g
pcnlr           double  %10.0g
pctr            double  %10.0g
pdvc            double  %10.0g
pi              double  %10.0g
pidom           double  %10.0g
pifo            double  %10.0g
pll             double  %10.0g
pltbl           double  %10.0g
pnca            double  %10.0g
pncad           double  %10.0g
pncaeps         double  %10.0g
pncia           double  %10.0g
pncid           double  %10.0g
pncieps         double  %10.0g
pncip           double  %10.0g
pncwia          double  %10.0g
pncwid          double  %10.0g
pncwieps        double  %10.0g
pncwip          double  %10.0g
pnlbl           double  %10.0g
pnli            double  %10.0g
pnrsho          double  %10.0g
pobl            double  %10.0g
ppcbl           double  %10.0g
ppegt           double  %10.0g
ppenb           double  %10.0g
ppenc           double  %10.0g
ppenli          double  %10.0g
ppenls          double  %10.0g
ppenme          double  %10.0g
ppennr          double  %10.0g
ppeno           double  %10.0g
ppent           double  %10.0g
ppevbb          double  %10.0g
ppeveb          double  %10.0g
ppevo           double  %10.0g
ppevr           double  %10.0g
pppabl          double  %10.0g
ppphbl          double  %10.0g
pppobl          double  %10.0g
ppptbl          double  %10.0g
prc             double  %10.0g
prca            double  %10.0g
prcad           double  %10.0g
prcaeps         double  %10.0g
prebl           double  %10.0g
pri             double  %10.0g
prodv           double  %10.0g
prsho           double  %10.0g
prstkc          double  %10.0g
prstkcc         double  %10.0g
prstkpc         double  %10.0g
prvt            double  %10.0g
pstk            double  %10.0g
pstkc           double  %10.0g
pstkl           double  %10.0g
pstkn           double  %10.0g
pstkr           double  %10.0g
pstkrv          double  %10.0g
ptbl            double  %10.0g
ptran           double  %10.0g
pvcl            double  %10.0g
pvo             double  %10.0g
pvon            double  %10.0g
pvpl            double  %10.0g
pvt             double  %10.0g
pwoi            double  %10.0g
radp            double  %10.0g
ragr            double  %10.0g
rari            double  %10.0g
rati            double  %10.0g
rca             double  %10.0g
rcd             double  %10.0g
rceps           double  %10.0g
rcl             double  %10.0g
rcp             double  %10.0g
rdip            double  %10.0g
rdipa           double  %10.0g
rdipd           double  %10.0g
rdipeps         double  %10.0g
rdp             double  %10.0g
re              double  %10.0g
rea             double  %10.0g
reajo           double  %10.0g
recch           double  %10.0g
recco           double  %10.0g
recd            double  %10.0g
rect            double  %10.0g
recta           double  %10.0g
rectr           double  %10.0g
recub           double  %10.0g
ret             double  %10.0g
reuna           double  %10.0g
reunr           double  %10.0g
revt            double  %10.0g
ris             double  %10.0g
rll             double  %10.0g
rlo             double  %10.0g
rlp             double  %10.0g
rlri            double  %10.0g
rlt             double  %10.0g
rmum            double  %10.0g
rpag            double  %10.0g
rra             double  %10.0g
rrd             double  %10.0g
rreps           double  %10.0g
rrp             double  %10.0g
rstche          double  %10.0g
rstchelt        double  %10.0g
rvbci           double  %10.0g
rvbpi           double  %10.0g
rvbti           double  %10.0g
rvdo            double  %10.0g
rvdt            double  %10.0g
rveqt           double  %10.0g
rvlrv           double  %10.0g
rvno            double  %10.0g
rvnt            double  %10.0g
rvri            double  %10.0g
rvsi            double  %10.0g
rvti            double  %10.0g
rvtxr           double  %10.0g
rvupi           double  %10.0g
rvutx           double  %10.0g
saa             double  %10.0g
sal             double  %10.0g
sale            double  %10.0g
salepfc         double  %10.0g
salepfp         double  %10.0g
sbdc            double  %10.0g
sc              double  %10.0g
sco             double  %10.0g
scstkc          double  %10.0g
secu            double  %10.0g
seq             double  %10.0g
seqo            double  %10.0g
seta            double  %10.0g
setd            double  %10.0g
seteps          double  %10.0g
setp            double  %10.0g
siv             double  %10.0g
spce            double  %10.0g
spced           double  %10.0g
spceeps         double  %10.0g
spi             double  %10.0g
spid            double  %10.0g
spieps          double  %10.0g
spioa           double  %10.0g
spiop           double  %10.0g
sppe            double  %10.0g
sppiv           double  %10.0g
spstkc          double  %10.0g
sret            double  %10.0g
srt             double  %10.0g
ssnp            double  %10.0g
sstk            double  %10.0g
stbo            double  %10.0g
stio            double  %10.0g
stkco           double  %10.0g
stkcpa          double  %10.0g
tdc             double  %10.0g
tdscd           double  %10.0g
tdsce           double  %10.0g
tdsg            double  %10.0g
tdslg           double  %10.0g
tdsmm           double  %10.0g
tdsng           double  %10.0g
tdso            double  %10.0g
tdss            double  %10.0g
tdst            double  %10.0g
teq             double  %10.0g
tf              double  %10.0g
tfva            double  %10.0g
tfvce           double  %10.0g
tfvl            double  %10.0g
tie             double  %10.0g
tii             double  %10.0g
tlcf            double  %10.0g
transa          double  %10.0g
tsa             double  %10.0g
tsafc           double  %10.0g
tso             double  %10.0g
tstk            double  %10.0g
tstkc           double  %10.0g
tstkme          double  %10.0g
tstkn           double  %10.0g
tstkp           double  %10.0g
txach           double  %10.0g
txbco           double  %10.0g
txbcof          double  %10.0g
txc             double  %10.0g
txdb            double  %10.0g
txdba           double  %10.0g
txdbca          double  %10.0g
txdbcl          double  %10.0g
txdc            double  %10.0g
txdfed          double  %10.0g
txdfo           double  %10.0g
txdi            double  %10.0g
txditc          double  %10.0g
txds            double  %10.0g
txeqa           double  %10.0g
txeqii          double  %10.0g
txfed           double  %10.0g
txfo            double  %10.0g
txndb           double  %10.0g
txndba          double  %10.0g
txndbl          double  %10.0g
txndbr          double  %10.0g
txo             double  %10.0g
txp             double  %10.0g
txpd            double  %10.0g
txr             double  %10.0g
txs             double  %10.0g
txt             double  %10.0g
txtubadjust     double  %10.0g
txtubbegin      double  %10.0g
txtubend        double  %10.0g
txtubmax        double  %10.0g
txtubmin        double  %10.0g
txtubposdec     double  %10.0g
txtubposinc     double  %10.0g
txtubpospdec    double  %10.0g
txtubpospinc    double  %10.0g
txtubsettle     double  %10.0g
txtubsoflimit   double  %10.0g
txtubtxtr       double  %10.0g
txtubxintbs     double  %10.0g
txtubxintis     double  %10.0g
txva            double  %10.0g
txw             double  %10.0g
uaoloch         double  %10.0g
uaox            double  %10.0g
uapt            double  %10.0g
ucaps           double  %10.0g
uccons          double  %10.0g
uceq            double  %10.0g
ucustad         double  %10.0g
udcopres        double  %10.0g
udd             double  %10.0g
udfcc           double  %10.0g
udmb            double  %10.0g
udolt           double  %10.0g
udpco           double  %10.0g
udpfa           double  %10.0g
udvp            double  %10.0g
ufretsd         double  %10.0g
ugi             double  %10.0g
ui              double  %10.0g
uinvt           double  %10.0g
ulcm            double  %10.0g
ulco            double  %10.0g
uniami          double  %10.0g
unl             double  %10.0g
unnp            double  %10.0g
unnpl           double  %10.0g
unopinc         double  %10.0g
unwcc           double  %10.0g
uois            double  %10.0g
uopi            double  %10.0g
uopres          double  %10.0g
updvp           double  %10.0g
upmcstk         double  %10.0g
upmpf           double  %10.0g
upmpfs          double  %10.0g
upmsubp         double  %10.0g
upstk           double  %10.0g
upstkc          double  %10.0g
upstksf         double  %10.0g
urect           double  %10.0g
urectr          double  %10.0g
urevub          double  %10.0g
uspi            double  %10.0g
ustdnc          double  %10.0g
usubdvp         double  %10.0g
usubpstk        double  %10.0g
utfdoc          double  %10.0g
utfosc          double  %10.0g
utme            double  %10.0g
utxfed          double  %10.0g
uwkcapc         double  %10.0g
uxinst          double  %10.0g
uxintd          double  %10.0g
vpac            double  %10.0g
vpo             double  %10.0g
wcap            double  %10.0g
wcapc           double  %10.0g
wcapch          double  %10.0g
wda             double  %10.0g
wdd             double  %10.0g
wdeps           double  %10.0g
wdp             double  %10.0g
xacc            double  %10.0g
xad             double  %10.0g
xago            double  %10.0g
xagt            double  %10.0g
xcom            double  %10.0g
xcomi           double  %10.0g
xdepl           double  %10.0g
xdp             double  %10.0g
xdvre           double  %10.0g
xeqo            double  %10.0g
xi              double  %10.0g
xido            double  %10.0g
xidoc           double  %10.0g
xindb           double  %10.0g
xindc           double  %10.0g
xins            double  %10.0g
xinst           double  %10.0g
xint            double  %10.0g
xintd           double  %10.0g
xintopt         double  %10.0g
xivi            double  %10.0g
xivre           double  %10.0g
xlr             double  %10.0g
xnbi            double  %10.0g
xnf             double  %10.0g
xnins           double  %10.0g
xnitb           double  %10.0g
xobd            double  %10.0g
xoi             double  %10.0g
xopr            double  %10.0g
xoprar          double  %10.0g
xoptd           double  %10.0g
xopteps         double  %10.0g
xore            double  %10.0g
xpp             double  %10.0g
xpr             double  %10.0g
xrd             double  %10.0g
xrdp            double  %10.0g
xrent           double  %10.0g
xs              double  %10.0g
xsga            double  %10.0g
xstf            double  %10.0g
xstfo           double  %10.0g
xstfws          double  %10.0g
xt              double  %10.0g
xuw             double  %10.0g
xuwli           double  %10.0g
xuwnli          double  %10.0g
xuwoi           double  %10.0g
xuwrei          double  %10.0g
xuwti           double  %10.0g
iid             str2    %9s
exchg           double  %10.0g
cik             str10   %10s
costat          str1    %9s
fic             str3    %9s
naicsh          double  %10.0g
sich            double  %10.0g
cshtr_c         double  %10.0g
dvpsp_c         double  %10.0g
dvpsx_c         double  %10.0g
prcc_c          double  %10.0g
prch_c          double  %10.0g
prcl_c          double  %10.0g
adjex_c         double  %10.0g
cshtr_f         double  %10.0g
dvpsp_f         double  %10.0g
dvpsx_f         double  %10.0g
mkvalt          double  %10.0g
prcc_f          double  %10.0g
prch_f          double  %10.0g
prcl_f          double  %10.0g
adjex_f         double  %10.0g
rank            double  %10.0g
au              str2    %9s
auop            str1    %9s
auopic          str1    %9s
ceoso           str1    %9s
cfoso           str1    %9s
--------------------------------------------------------------------------------------------------------
Sorted by:
r; t=0.05 12:07:34

.
